/**
 * Persisted WireGuard ingress configuration.
 *
 * Storage mirrors `namedTunnelConfig.ts`: rows live in `key_value` (namespace `settings`) under
 * keys that start with `_`, which `getSettings()` skips, so nothing here can leak through
 * GET /api/settings, PATCH responses or settings audit diffs.
 *
 * - `_wireguardServerConfig`: the non-secret model (interface, address, port, endpoint host, DNS,
 *   peers with their PUBLIC keys) plus the server public key.
 * - `_wireguardServerPrivateKey`: the server private key, through `encrypt()`.
 * - `_wireguardPsk:<peerId>`: one preshared key per peer, through `encrypt()`.
 *
 * Peer PRIVATE keys are generated by `addWireGuardPeer()` and handed back to its caller once. They
 * are never written anywhere; only the peer's public key is kept. The server private key and the
 * preshared keys are only readable through `readWireGuardServerConfSource()`, which exists for the
 * authenticated config download.
 */

import { randomBytes } from "node:crypto";
import { getDbInstance } from "./core";
import { decrypt, encrypt } from "./encryption";
import { derivePublicKey, generateKeyPair, generatePresharedKey } from "@/lib/wireguard/keys";
import {
  WireGuardConfigError,
  allocatePeerAddress,
  defaultServerModel,
  type WireGuardPeer,
  type WireGuardServerModel,
} from "@/lib/wireguard/serverConfig";

const CONFIG_KEY = "_wireguardServerConfig";
const SERVER_KEY_KEY = "_wireguardServerPrivateKey";
const PSK_KEY_PREFIX = "_wireguardPsk:";

export type StoredWireGuardConfig = WireGuardServerModel & { serverPublicKey: string };

function readRaw(key: string): string | null {
  const row = getDbInstance()
    .prepare("SELECT value FROM key_value WHERE namespace = 'settings' AND key = ?")
    .get(key) as { value?: unknown } | undefined;
  return row && typeof row.value === "string" ? row.value : null;
}

function writeRaw(key: string, jsonValue: string): void {
  getDbInstance()
    .prepare("INSERT OR REPLACE INTO key_value (namespace, key, value) VALUES ('settings', ?, ?)")
    .run(key, jsonValue);
}

function deleteRaw(key: string): void {
  getDbInstance()
    .prepare("DELETE FROM key_value WHERE namespace = 'settings' AND key = ?")
    .run(key);
}

function readSecret(key: string): string {
  const raw = readRaw(key);
  if (!raw) return "";
  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed !== "string" || !parsed) return "";
    return decrypt(parsed) ?? "";
  } catch {
    return "";
  }
}

function writeSecret(key: string, secret: string): void {
  writeRaw(key, JSON.stringify(encrypt(secret) as string));
}

function isPeer(value: unknown): value is WireGuardPeer {
  if (!value || typeof value !== "object") return false;
  const peer = value as Record<string, unknown>;
  return (
    typeof peer.id === "string" &&
    typeof peer.name === "string" &&
    typeof peer.publicKey === "string" &&
    typeof peer.allowedIp === "string"
  );
}

/** The stored model without any secret, or null before the first save. */
export function readWireGuardConfig(): StoredWireGuardConfig | null {
  const raw = readRaw(CONFIG_KEY);
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    if (!parsed || typeof parsed !== "object" || typeof parsed.serverPublicKey !== "string") {
      return null;
    }
    const base = defaultServerModel();
    const peers = Array.isArray(parsed.peers) ? parsed.peers.filter(isPeer) : [];
    return {
      interfaceName: typeof parsed.interfaceName === "string" ? parsed.interfaceName : base.interfaceName,
      address: typeof parsed.address === "string" ? parsed.address : base.address,
      listenPort: typeof parsed.listenPort === "number" ? parsed.listenPort : base.listenPort,
      endpointHost: typeof parsed.endpointHost === "string" ? parsed.endpointHost : "",
      dns: typeof parsed.dns === "string" ? parsed.dns : "",
      serverPublicKey: parsed.serverPublicKey,
      peers: peers.map((peer) => ({
        id: peer.id,
        name: peer.name,
        publicKey: peer.publicKey,
        allowedIp: peer.allowedIp,
        createdAt: typeof peer.createdAt === "string" ? peer.createdAt : "",
        hasPresharedKey: peer.hasPresharedKey === true,
      })),
    };
  } catch {
    return null;
  }
}

function writeConfig(config: StoredWireGuardConfig): void {
  writeRaw(
    CONFIG_KEY,
    JSON.stringify({
      interfaceName: config.interfaceName,
      address: config.address,
      listenPort: config.listenPort,
      endpointHost: config.endpointHost,
      dns: config.dns,
      serverPublicKey: config.serverPublicKey,
      peers: config.peers.map((peer) => ({
        id: peer.id,
        name: peer.name,
        publicKey: peer.publicKey,
        allowedIp: peer.allowedIp,
        createdAt: peer.createdAt,
        hasPresharedKey: peer.hasPresharedKey === true,
      })),
    })
  );
}

export type SaveWireGuardConfigInput = {
  endpointHost: string;
  interfaceName?: string;
  address?: string;
  listenPort?: number;
  dns?: string;
};

/**
 * Save the server settings. The first save generates the server keypair; later saves never touch
 * it (rotation is its own explicit operation). The tunnel address cannot change while peers exist,
 * because every issued peer file embeds it.
 */
export function saveWireGuardConfig(input: SaveWireGuardConfigInput): {
  config: StoredWireGuardConfig;
  serverKeyGenerated: boolean;
} {
  const db = getDbInstance();
  return db.transaction(() => {
    const existing = readWireGuardConfig();
    if (existing && input.address !== undefined && input.address !== existing.address) {
      if (existing.peers.length > 0) {
        throw new WireGuardConfigError(
          "address_locked",
          "Remove all peers before changing the tunnel address."
        );
      }
    }

    let serverKeyGenerated = false;
    let serverPublicKey = existing?.serverPublicKey ?? "";
    if (!existing || !readSecret(SERVER_KEY_KEY)) {
      const pair = generateKeyPair();
      writeSecret(SERVER_KEY_KEY, pair.privateKey);
      serverPublicKey = pair.publicKey;
      serverKeyGenerated = true;
    }

    const base = existing ?? { ...defaultServerModel(), serverPublicKey };
    const config: StoredWireGuardConfig = {
      ...base,
      serverPublicKey,
      endpointHost: input.endpointHost,
      interfaceName: input.interfaceName ?? base.interfaceName,
      address: input.address ?? base.address,
      listenPort: input.listenPort ?? base.listenPort,
      dns: input.dns ?? base.dns,
    };
    writeConfig(config);
    return { config, serverKeyGenerated };
  })();
}

/** Replace the server keypair. Every issued peer file then points at a stale server public key. */
export function rotateWireGuardServerKey(): StoredWireGuardConfig {
  const db = getDbInstance();
  return db.transaction(() => {
    const existing = readWireGuardConfig();
    if (!existing) {
      throw new WireGuardConfigError("not_configured", "Save the WireGuard settings first.");
    }
    const pair = generateKeyPair();
    writeSecret(SERVER_KEY_KEY, pair.privateKey);
    const config = { ...existing, serverPublicKey: pair.publicKey };
    writeConfig(config);
    return config;
  })();
}

export type AddedWireGuardPeer = {
  peer: WireGuardPeer;
  /** Returned to the caller once and never stored. */
  peerPrivateKey: string;
  /** Present when a preshared key was generated; the encrypted copy is kept for the server file. */
  presharedKey?: string;
  config: StoredWireGuardConfig;
};

/**
 * Create a peer: allocate the next free /32, generate its keypair (and optionally a preshared
 * key), persist ONLY the public key and the encrypted preshared key, and return the private key to
 * the caller. The allocation and the write share one transaction, so two concurrent adds cannot
 * receive the same address.
 */
export function addWireGuardPeer(input: { name: string; usePresharedKey: boolean }): AddedWireGuardPeer {
  const db = getDbInstance();
  return db.transaction(() => {
    const existing = readWireGuardConfig();
    if (!existing) {
      throw new WireGuardConfigError("not_configured", "Save the WireGuard settings first.");
    }
    if (!existing.endpointHost) {
      throw new WireGuardConfigError("endpoint_required", "Set the endpoint host before adding peers");
    }
    const allowedIp = allocatePeerAddress(existing);
    const pair = generateKeyPair();
    const presharedKey = input.usePresharedKey ? generatePresharedKey() : undefined;
    const peer: WireGuardPeer = {
      id: `peer_${randomBytes(6).toString("hex")}`,
      name: input.name,
      publicKey: pair.publicKey,
      allowedIp,
      createdAt: new Date().toISOString(),
      hasPresharedKey: presharedKey !== undefined,
    };
    if (presharedKey !== undefined) writeSecret(`${PSK_KEY_PREFIX}${peer.id}`, presharedKey);
    const config = { ...existing, peers: [...existing.peers, peer] };
    writeConfig(config);
    return { peer, peerPrivateKey: pair.privateKey, presharedKey, config };
  })();
}

/** Remove a peer and its preshared key. False when no such peer exists. */
export function removeWireGuardPeer(id: string): boolean {
  const db = getDbInstance();
  return db.transaction(() => {
    const existing = readWireGuardConfig();
    if (!existing || !existing.peers.some((peer) => peer.id === id)) return false;
    deleteRaw(`${PSK_KEY_PREFIX}${id}`);
    writeConfig({ ...existing, peers: existing.peers.filter((peer) => peer.id !== id) });
    return true;
  })();
}

/**
 * The model with every preshared key decrypted, plus the server private key: exactly what the
 * server file needs. Callers must never log or return this except as the authenticated download.
 * Null before the first save or when the server key is unreadable.
 */
export function readWireGuardServerConfSource(): {
  model: WireGuardServerModel;
  serverPrivateKey: string;
} | null {
  const config = readWireGuardConfig();
  if (!config) return null;
  const serverPrivateKey = readSecret(SERVER_KEY_KEY);
  if (!serverPrivateKey) return null;
  // A stored key that no longer matches the published public key means the row was tampered with.
  try {
    if (derivePublicKey(serverPrivateKey) !== config.serverPublicKey) return null;
  } catch {
    return null;
  }
  const peers: WireGuardPeer[] = [];
  for (const peer of config.peers) {
    if (!peer.hasPresharedKey) {
      peers.push({ ...peer });
      continue;
    }
    // A peer that should have a preshared key but whose key is unreadable would get a server
    // file that silently rejects it, so refuse to render at all.
    const presharedKey = readSecret(`${PSK_KEY_PREFIX}${peer.id}`);
    if (!presharedKey) return null;
    peers.push({ ...peer, presharedKey });
  }
  return {
    model: {
      interfaceName: config.interfaceName,
      address: config.address,
      listenPort: config.listenPort,
      endpointHost: config.endpointHost,
      dns: config.dns,
      peers,
    },
    serverPrivateKey,
  };
}
