import { execFile } from "node:child_process";
import { lstat, readFile, rename, unlink, writeFile } from "node:fs/promises";
import { homedir, networkInterfaces } from "node:os";
import { dirname, join, resolve } from "node:path";
import { randomUUID } from "node:crypto";
import { promisify } from "node:util";

export type NetworkAccessMode = "local" | "lan";
const unitPath = () => join(homedir(), ".config/systemd/user/red-router.service");
const hosts = { local: "127.0.0.1", lan: "0.0.0.0" } as const;
const run = promisify(execFile);
let changing = false;
let restartError: string | null = null;

export class NetworkAccessError extends Error {
  constructor(public code: "unsupported" | "busy" | "changed" | "apply_failed") {
    super(code);
  }
}

type Options = {
  path?: string;
  env?: NodeJS.ProcessEnv;
  platform?: NodeJS.Platform;
  interfaces?: ReturnType<typeof networkInterfaces>;
  execute?: (args: string[]) => Promise<unknown>;
  schedule?: (action: () => Promise<void>) => void;
};

function portNumber(value: string | undefined, fallback = 25050) {
  const n = Number(value);
  return Number.isInteger(n) && n > 0 && n <= 65535 ? n : fallback;
}

export function parseManagedNetworkUnit(text: string) {
  if (!text.includes("Description=RedRouter AI routing gateway")) return null;
  const port = Number(/^Environment="RED_ROUTER_PORT=(\d+)"$/m.exec(text)?.[1]);
  const host = /^Environment="RED_ROUTER_SERVER_HOST=([a-zA-Z0-9.:[\]-]+)"$/m.exec(text)?.[1];
  const data = /^Environment=("DATA_DIR=.+")$/m.exec(text)?.[1];
  if (!host || !data || !Number.isInteger(port) || port < 1 || port > 65535) return null;
  try {
    const dataDir = JSON.parse(data).replaceAll("%%", "%").slice("DATA_DIR=".length);
    // Only units generated by our installer, with one explicit host argument, can be edited.
    const starts = text.match(/^ExecStart=.*$/gm) || [];
    if (
      starts.length !== 1 ||
      !starts[0].includes('"serve"') ||
      !starts[0].includes('"--host" "' + host + '"')
    )
      return null;
    return { host, port, dataDir };
  } catch {
    return null;
  }
}

export function replaceManagedNetworkHost(text: string, host: string) {
  const saved = parseManagedNetworkUnit(text);
  if (!saved || !Object.values(hosts).includes(host as typeof hosts.local)) {
    throw new NetworkAccessError("unsupported");
  }
  return text
    .replace(/^ExecStart=.*$/m, (line) =>
      line.replace('"--host" "' + saved.host + '"', '"--host" "' + host + '"')
    )
    .replace(
      /^Environment="RED_ROUTER_SERVER_HOST=[^"\n]+"$/m,
      `Environment="RED_ROUTER_SERVER_HOST=${host}"`
    );
}

export function localNetworkAddresses(interfaces = networkInterfaces()) {
  const addresses = new Set<string>();
  for (const [name, entries] of Object.entries(interfaces)) {
    if (/^(lo$|docker|veth|br-|virbr)/i.test(name)) continue;
    for (const entry of entries || []) {
      if (entry.internal || entry.family !== "IPv4") continue;
      const parts = entry.address.split(".").map(Number);
      if (
        parts.length === 4 &&
        (parts[0] === 10 ||
          (parts[0] === 192 && parts[1] === 168) ||
          (parts[0] === 172 && parts[1] >= 16 && parts[1] <= 31))
      )
        addresses.add(entry.address);
    }
  }
  return [...addresses].sort().slice(0, 8);
}

export async function readNetworkAccessStatus(options: Options = {}) {
  const env = options.env || process.env;
  const host = env.RED_ROUTER_SERVER_HOST || env.OMNIROUTE_SERVER_HOST || "127.0.0.1";
  const port = portNumber(env.PORT || env.RED_ROUTER_PORT);
  const apiPort = portNumber(env.API_PORT, port);
  let saved: ReturnType<typeof parseManagedNetworkUnit> = null;
  try {
    const path = options.path || unitPath();
    if ((await lstat(path)).isFile()) saved = parseManagedNetworkUnit(await readFile(path, "utf8"));
  } catch {
    /* Unmanaged installs still report their effective listener. */
  }
  const managed =
    (options.platform || process.platform) === "linux" &&
    Boolean(
      env.INVOCATION_ID &&
      saved &&
      saved.port === port &&
      env.DATA_DIR &&
      resolve(saved.dataDir) === resolve(env.DATA_DIR)
    );
  const scheme = env.OMNIROUTE_TLS_CERT && env.OMNIROUTE_TLS_KEY ? "https" : "http";
  return {
    host,
    port,
    mode:
      host === "127.0.0.1" || host === "localhost" || host === "::1"
        ? "local"
        : host === "0.0.0.0" || host === "::"
          ? "lan"
          : "custom",
    managed,
    configuredHost: managed ? saved!.host : host,
    pendingRestart: managed && saved!.host !== host,
    restartError,
    addresses: localNetworkAddresses(options.interfaces).map((address) => ({
      address,
      dashboardUrl: `${scheme}://${address}:${port}`,
      apiBaseUrl: `${scheme}://${address}:${apiPort}/v1`,
      healthUrl: `${scheme}://${address}:${port}/healthz`,
    })),
  };
}

async function replaceUnit(path: string, expected: string, updated: string) {
  if ((await readFile(path, "utf8")) !== expected) throw new NetworkAccessError("changed");
  const info = await lstat(path);
  if (!info.isFile()) throw new NetworkAccessError("unsupported");
  const temp = join(dirname(path), `.red-router-network-${randomUUID()}.tmp`);
  try {
    await writeFile(temp, updated, { mode: info.mode & 0o777, flag: "wx" });
    if ((await readFile(path, "utf8")) !== expected) throw new NetworkAccessError("changed");
    await rename(temp, path);
  } finally {
    await unlink(temp).catch(() => {});
  }
}

export async function applyNetworkAccess(mode: NetworkAccessMode, options: Options = {}) {
  if (!Object.hasOwn(hosts, mode)) throw new NetworkAccessError("unsupported");
  if (changing) throw new NetworkAccessError("busy");
  changing = true;
  let scheduled = false;
  const path = options.path || unitPath();
  const execute = options.execute || ((args) => run("systemctl", args, { timeout: 15000 }));
  try {
    const status = await readNetworkAccessStatus(options);
    if (!status.managed) throw new NetworkAccessError("unsupported");
    const original = await readFile(path, "utf8");
    const updated = replaceManagedNetworkHost(original, hosts[mode]);
    restartError = null;
    if (status.host === hosts[mode] && status.configuredHost === hosts[mode]) return status;
    await replaceUnit(path, original, updated);
    try {
      await execute(["--user", "daemon-reload"]);
    } catch {
      await replaceUnit(path, updated, original);
      await execute(["--user", "daemon-reload"]).catch(() => {});
      throw new NetworkAccessError("apply_failed");
    }
    const restart = async () => {
      try {
        // Queue the restart with the service manager. A child in our cgroup must not
        // wait for the service it belongs to to stop and start.
        await execute(["--user", "--no-block", "restart", "red-router.service"]);
      } catch {
        restartError = "The service manager rejected the restart. Retry the change.";
        try {
          await replaceUnit(path, updated, original);
          await execute(["--user", "daemon-reload"]);
        } catch {
          /* Preserve concurrent changes; never overwrite them during rollback. */
        }
      } finally {
        changing = false;
      }
    };
    (
      options.schedule ||
      ((action) => {
        setTimeout(() => {
          void action();
        }, 750);
      })
    )(restart);
    scheduled = true;
    return { ...status, configuredHost: hosts[mode], pendingRestart: true };
  } finally {
    if (!scheduled) changing = false;
  }
}
