/** 9router Windsurf catalog and Codeium model UIDs (upstream/master snapshot). */
const WIND_SURF_MODELS = [
  ["swe-1.6-fast", "swe-1-6-fast"],
  ["swe-1.6", "swe-1-6"],
  ["swe-1.5-fast", "swe-1-5-fast"],
  ["swe-1.5", "swe-1-5"],
  ["claude-opus-4.7-max", "claude-opus-4-7-max"],
  ["claude-opus-4.7-xhigh", "claude-opus-4-7-xhigh"],
  ["claude-opus-4.7-high", "claude-opus-4-7-high"],
  ["claude-opus-4.7-medium", "claude-opus-4-7-medium"],
  ["claude-opus-4.7-low", "claude-opus-4-7-low"],
  ["claude-opus-4.7-review", "opus-4-7-review"],
  ["claude-sonnet-4.6-thinking-1m", "claude-sonnet-4-6-thinking-1m"],
  ["claude-sonnet-4.6-1m", "claude-sonnet-4-6-1m"],
  ["claude-sonnet-4.6-thinking", "claude-sonnet-4-6-thinking"],
  ["claude-sonnet-4.6", "claude-sonnet-4-6"],
  ["claude-opus-4.6-thinking", "claude-opus-4-6-thinking"],
  ["claude-opus-4.6", "claude-opus-4-6"],
  ["claude-opus-4.5-thinking", "MODEL_CLAUDE_4_5_OPUS_THINKING"],
  ["claude-opus-4.5", "MODEL_CLAUDE_4_5_OPUS"],
  ["claude-sonnet-4.5-thinking", "MODEL_PRIVATE_3"],
  ["claude-sonnet-4.5", "MODEL_PRIVATE_2"],
  ["claude-haiku-4.5", "MODEL_PRIVATE_11"],
  ["gpt-5.5-xhigh-fast", "gpt-5-5-xhigh-priority"],
  ["gpt-5.5-xhigh", "gpt-5-5-xhigh"],
  ["gpt-5.5-high-fast", "gpt-5-5-high-priority"],
  ["gpt-5.5-high", "gpt-5-5-high"],
  ["gpt-5.5-medium-fast", "gpt-5-5-medium-priority"],
  ["gpt-5.5-medium", "gpt-5-5-medium"],
  ["gpt-5.5-low-fast", "gpt-5-5-low-priority"],
  ["gpt-5.5-low", "gpt-5-5-low"],
  ["gpt-5.5-none-fast", "gpt-5-5-none-priority"],
  ["gpt-5.5-none", "gpt-5-5-none"],
  ["gpt-5.4-xhigh-fast", "gpt-5-4-xhigh-priority"],
  ["gpt-5.4-xhigh", "gpt-5-4-xhigh"],
  ["gpt-5.4-high-fast", "gpt-5-4-high-priority"],
  ["gpt-5.4-high", "gpt-5-4-high"],
  ["gpt-5.4-medium-fast", "gpt-5-4-medium-priority"],
  ["gpt-5.4-medium", "gpt-5-4-medium"],
  ["gpt-5.4-low-fast", "gpt-5-4-low-priority"],
  ["gpt-5.4-low", "gpt-5-4-low"],
  ["gpt-5.4-none-fast", "gpt-5-4-none-priority"],
  ["gpt-5.4-none", "gpt-5-4-none"],
  ["gpt-5.4-mini-xhigh", "gpt-5-4-mini-xhigh"],
  ["gpt-5.4-mini-high", "gpt-5-4-mini-high"],
  ["gpt-5.4-mini-medium", "gpt-5-4-mini-medium"],
  ["gpt-5.4-mini-low", "gpt-5-4-mini-low"],
  ["gpt-5.3-codex-xhigh-fast", "gpt-5-3-codex-xhigh-priority"],
  ["gpt-5.3-codex-xhigh", "gpt-5-3-codex-xhigh"],
  ["gpt-5.3-codex-high-fast", "gpt-5-3-codex-high-priority"],
  ["gpt-5.3-codex-high", "gpt-5-3-codex-high"],
  ["gpt-5.3-codex-medium-fast", "gpt-5-3-codex-medium-priority"],
  ["gpt-5.3-codex-medium", "gpt-5-3-codex-medium"],
  ["gpt-5.3-codex-low-fast", "gpt-5-3-codex-low-priority"],
  ["gpt-5.3-codex-low", "gpt-5-3-codex-low"],
  ["gpt-5.2-xhigh", "MODEL_GPT_5_2_XHIGH"],
  ["gpt-5.2-high", "MODEL_GPT_5_2_HIGH"],
  ["gpt-5.2-medium", "MODEL_GPT_5_2_MEDIUM"],
  ["gpt-5.2-low", "MODEL_GPT_5_2_LOW"],
  ["gpt-5.2-none", "MODEL_GPT_5_2_NONE"],
  ["gpt-5", "gpt-5"],
  ["gpt-4.1", "MODEL_CHAT_GPT_4_1_2025_04_14"],
  ["gpt-4.1-mini", "gpt-4.1-mini"],
  ["gpt-4.1-nano", "gpt-4.1-nano"],
  ["gpt-4o", "MODEL_CHAT_GPT_4O_2024_08_06"],
  ["gpt-4o-mini", "gpt-4o-mini"],
  ["gemini-3.1-pro-high", "gemini-3-1-pro-high"],
  ["gemini-3.1-pro-low", "gemini-3-1-pro-low"],
  ["gemini-3.0-flash-high", "MODEL_GOOGLE_GEMINI_3_0_FLASH_HIGH"],
  ["gemini-3.0-flash-medium", "MODEL_GOOGLE_GEMINI_3_0_FLASH_MEDIUM"],
  ["gemini-3.0-flash-low", "MODEL_GOOGLE_GEMINI_3_0_FLASH_LOW"],
  ["gemini-3.0-flash-minimal", "MODEL_GOOGLE_GEMINI_3_0_FLASH_MINIMAL"],
  ["gemini-2.5-pro", "MODEL_GOOGLE_GEMINI_2_5_PRO"],
  ["deepseek-v4", "deepseek-v4"],
  ["kimi-k2.6", "kimi-k2-6"],
  ["kimi-k2.5", "kimi-k2-5"],
  ["glm-5.1", "glm-5-1"],
] as const;

export const WINDSURF_MODELS = WIND_SURF_MODELS.map(([id]) => ({ id, name: id }));
const MODEL_UIDS = new Map<string, string>(WIND_SURF_MODELS);

export function resolveWindsurfModelUid(model: string): string | null {
  return MODEL_UIDS.get(model) ?? null;
}
