// Material Symbols name -> lucide glyph. Every name the dashboard renders must
// be listed here; tests/unit/icons-lucide.test.js enforces that.
import {
  Activity,
  Aperture,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpFromLine,
  AudioLines,
  AudioWaveform,
  BadgeCheck,
  BadgePlus,
  Ban,
  Bird,
  Blend,
  BookOpen,
  Bot,
  Braces,
  Brackets,
  Brain,
  BrainCircuit,
  BrainCog,
  Brush,
  BuildingComplex,
  Cast,
  ChartColumn,
  ChartPie,
  ChartScatter,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CirclePause,
  CirclePlay,
  CircleQuestionMark,
  CircleStop,
  CircleUserRound,
  CircleX,
  CircuitBoard,
  Clock,
  Cloud,
  CloudOff,
  CloudSync,
  CloudUpload,
  Cloudy,
  Code,
  Compass,
  Contrast,
  Cookie,
  Copy,
  Cpu,
  Database,
  Download,
  Droplet,
  Earth,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FaceSlightlySmiling,
  FileInput,
  FileOutput,
  FileText,
  FileUp,
  Film,
  Flame,
  FlaskConical,
  FolderOpen,
  FunnelX,
  Gauge,
  Gavel,
  Gem,
  Gift,
  Globe,
  GlobeLock,
  Hash,
  HeartHandshake,
  Hourglass,
  Image,
  Images,
  Info,
  Key,
  KeyRound,
  Languages,
  Laptop,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Link,
  List,
  ListChecks,
  ListOrdered,
  ListPlus,
  ListTodo,
  ListTree,
  LoaderCircle,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Menu,
  MessageSquare,
  Mic,
  Monitor,
  MonitorSmartphone,
  Moon,
  MoveHorizontal,
  Music,
  Network,
  NotebookPen,
  Package,
  Paperclip,
  Pencil,
  PiggyBank,
  Plane,
  Play,
  Plus,
  Power,
  Puzzle,
  RadioTower,
  RefreshCcw,
  RefreshCw,
  Rocket,
  RotateCcw,
  RotateCcwClock,
  RotateCw,
  Route,
  Router,
  Save,
  ScanQrCode,
  ScanSearch,
  ScrollText,
  Search,
  SearchCheck,
  SearchX,
  Send,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShieldLock,
  ShieldPlus,
  SlidersHorizontal,
  Sparkles,
  Speaker,
  Speech,
  Split,
  Square,
  SquareTerminal,
  Star,
  Store,
  Sun,
  TextSearch,
  ToggleLeft,
  ToggleRight,
  Trash,
  Triangle,
  TriangleAlert,
  Undo2,
  Unlink,
  Upload,
  User,
  Users,
  UtensilsCrossed,
  WavesHorizontal,
  WavesLadder,
  Waypoints,
  Webhook,
  Wifi,
  WifiOff,
  Wind,
  Wrench,
  WrapText,
  X,
  Zap,
} from "lucide-react";

export const MATERIAL_TO_LUCIDE = {
  account_circle: CircleUserRound,
  account_tree: ListTree,
  add: Plus,
  air: Wind,
  alt_route: Split,
  api: Webhook,
  apps: LayoutGrid,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  attach_file: Paperclip,
  auto_awesome: Sparkles,
  autorenew: RefreshCcw,
  bar_chart: ChartColumn,
  block: Ban,
  blur_on: Aperture,
  bolt: Zap,
  brush: Brush,
  build: Wrench,
  business: BuildingComplex,
  cancel: CircleX,
  cast: Cast,
  change_history: Triangle,
  chat: MessageSquare,
  check: Check,
  check_circle: CircleCheck,
  checklist: ListChecks,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud: Cloud,
  cloud_off: CloudOff,
  cloud_queue: Cloudy,
  cloud_sync: CloudSync,
  cloud_upload: CloudUpload,
  code: Code,
  computer: Laptop,
  content_copy: Copy,
  contrast: Contrast,
  cookie: Cookie,
  dark_mode: Moon,
  dashboard: LayoutDashboard,
  data_array: Brackets,
  data_object: Braces,
  data_usage: ChartPie,
  database: Database,
  delete: Trash,
  deployed_code: Package,
  developer_board: CircuitBoard,
  devices: MonitorSmartphone,
  diamond: Gem,
  dns: Server,
  download: Download,
  edit: Pencil,
  edit_note: NotebookPen,
  error: CircleAlert,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  extension: Puzzle,
  face: FaceSlightlySmiling,
  file_upload: Upload,
  filter_alt_off: FunnelX,
  flight: Plane,
  flutter_dash: Bird,
  folder_open: FolderOpen,
  gavel: Gavel,
  graphic_eq: AudioLines,
  grid_view: LayoutGrid,
  group: Users,
  group_work: Blend,
  health_and_safety: ShieldPlus,
  help: CircleQuestionMark,
  history: RotateCcwClock,
  hourglass_top: Hourglass,
  hub: Waypoints,
  image: Image,
  image_search: ScanSearch,
  info: Info,
  input: FileInput,
  key: Key,
  key_off: KeyRound,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_up: ChevronUp,
  lan: Network,
  language: Globe,
  layers: Layers,
  light_mode: Sun,
  link: Link,
  link_off: Unlink,
  list: List,
  local_fire_department: Flame,
  lock: Lock,
  lock_open: LockOpen,
  login: LogIn,
  logout: LogOut,
  low_priority: ListOrdered,
  manage_search: TextSearch,
  memory: Cpu,
  menu: Menu,
  menu_book: BookOpen,
  mic: Mic,
  money_off: Gift,
  monitor: Monitor,
  monitoring: Activity,
  more_horiz: Ellipsis,
  movie: Film,
  music_note: Music,
  neurology: BrainCircuit,
  new_releases: BadgePlus,
  open_in_new: ExternalLink,
  outbox: ArrowUpFromLine,
  output: FileOutput,
  pause_circle: CirclePause,
  perm_media: Images,
  person: User,
  picture_as_pdf: FileText,
  play_arrow: Play,
  play_circle: CirclePlay,
  playlist_add: ListPlus,
  policy: ScrollText,
  pool: WavesLadder,
  power_settings_new: Power,
  progress_activity: LoaderCircle,
  psychology: Brain,
  psychology_alt: BrainCog,
  public: Earth,
  qr_code_scanner: ScanQrCode,
  radio_button_unchecked: Circle,
  record_voice_over: Speech,
  refresh: RotateCw,
  restart_alt: RotateCcw,
  restaurant: UtensilsCrossed,
  restore: ArchiveRestore,
  rocket_launch: Rocket,
  route: Route,
  router: Router,
  rule: ListTodo,
  save: Save,
  saved_search: SearchCheck,
  savings: PiggyBank,
  scatter_plot: ChartScatter,
  schedule: Clock,
  science: FlaskConical,
  search: Search,
  search_off: SearchX,
  security: ShieldCheck,
  send: Send,
  settings: Settings,
  shield: Shield,
  shield_lock: ShieldLock,
  shield_with_heart: HeartHandshake,
  smart_toy: Bot,
  spatial_audio: AudioWaveform,
  speaker: Speaker,
  speed: Gauge,
  star: Star,
  stop: Square,
  stop_circle: CircleStop,
  storefront: Store,
  surfing: WavesHorizontal,
  sync: RefreshCw,
  sync_alt: ArrowLeftRight,
  tag: Hash,
  terminal: SquareTerminal,
  toggle_off: ToggleLeft,
  toggle_on: ToggleRight,
  translate: Languages,
  travel_explore: Compass,
  tune: SlidersHorizontal,
  undo: Undo2,
  upload: Upload,
  upload_file: FileUp,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  view_list: LayoutList,
  visibility: Eye,
  visibility_off: EyeOff,
  vpn_key: KeyRound,
  vpn_lock: GlobeLock,
  warning: TriangleAlert,
  water_drop: Droplet,
  width_full: MoveHorizontal,
  wifi: Wifi,
  wifi_off: WifiOff,
  wrap_text: WrapText,
  wifi_tethering: RadioTower,
};
